package cn.zcqq.base.model;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseProfile<M extends BaseProfile<M>> extends Model<M> implements IBean {

	public static final String table = "profile";

	public void setId(java.math.BigInteger id) {
		set("id", id);
	}

	public java.math.BigInteger getId() {
		return get("id");
	}

	public static final String UID = "uid";

	public void setUid(java.math.BigInteger uid) {
		set("uid", uid);
	}

	public java.math.BigInteger getUid() {
		return get("uid");
	}

	public static final String INFO = "info";

	public void setInfo(java.lang.String info) {
		set("info", info);
	}

	public java.lang.String getInfo() {
		return get("info");
	}

}
